name: fallstrick_mvc
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/Fallstrick/mvc

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fallstrick_hosting: ^0.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
